export type TransportMode = 'AIR' | 'OCEAN' | 'OCEAN_ROAD' | 'RAIL_OCEAN';

export type TruthClassification =
  | 'HISTORICAL_FACT'
  | 'LIVE_CURRENT_CONTEXT'
  | 'EXTERNAL_SANDBOX'
  | 'SIMULATED_IF_TODAY'
  | 'MOCK_CONNECTOR'
  | 'UNKNOWN';

export type ScenarioProvenance = {
  sourceTitle: string;
  sourceUrl: string;
  eventDate: string;
  publicationDate: 'UNKNOWN';
  retrievedDate: 'UNKNOWN';
  confidence: 'MEDIUM';
  classification: 'HISTORICAL_FACT';
};

export type Scenario = {
  id: string;
  shortName: string;
  headline: string;
  year: string;
  date: string;
  eventStartDate: string;
  category: string;
  place: string;
  coordinates: [number, number];
  origin: string;
  originCoordinates: [number, number];
  destination: string;
  destinationCoordinates: [number, number];
  product: string;
  promise: string;
  modeBefore: TransportMode;
  modeAfter: TransportMode;
  historicalImpact: string;
  sourceLabel: string;
  sourceUrl: string;
  routeBefore: string[];
  routeAfter: string[];
  recommendation: string;
  etaDelta: string;
  costDelta: string;
  documentChange: string;
  trackerBefore: string;
  trackerAfter: string;
  accent: string;
  provenance: ScenarioProvenance;
};

type ScenarioFixture = Omit<Scenario, 'provenance' | 'eventStartDate'>;

const scenarioFixtures: ScenarioFixture[] = [
  {
    id: 'EVT-012',
    shortName: 'Delta / CrowdStrike',
    headline: 'Uma atualização paralisa a malha aérea',
    year: '2024',
    date: '19–28 jul 2024',
    category: 'Pane global de TI',
    place: 'Atlanta, Estados Unidos',
    coordinates: [-84.4277, 33.6407],
    origin: 'Frankfurt',
    originCoordinates: [8.5706, 50.0333],
    destination: 'Atlanta',
    destinationCoordinates: [-84.4277, 33.6407],
    product: 'Peça AOG · 180 kg',
    promise: '14 horas',
    modeBefore: 'AIR',
    modeAfter: 'AIR',
    historicalImpact: 'Cancelamentos, atrasos e sistemas operacionais indisponíveis durante uma crise aguda de cinco dias.',
    sourceLabel: 'Alerta oficial da Delta',
    sourceUrl: 'https://www.delta.com/us/en/advisories/other-alerts/july-2024-travel-disruption',
    routeBefore: ['FRA', 'ATL'],
    routeAfter: ['FRA', 'LHR', 'ATL'],
    recommendation: 'Trocar a companhia via Londres e preservar o histórico do AWB original.',
    etaDelta: '+12–48 h',
    costDelta: '+US$ 4–12 mil',
    documentChange: 'Cancelar AWB original e emitir novo AWB',
    trackerBefore: 'Flight feed · companhia original',
    trackerAfter: 'Air express · conexão LHR',
    accent: '#ff7a93',
  },
  {
    id: 'EVT-014',
    shortName: 'Terremoto de Iskenderun',
    headline: 'O porto fecha e o conhecimento de embarque muda',
    year: '2023',
    date: '6 fev 2023',
    category: 'Terremoto + fechamento portuário',
    place: 'Iskenderun, Türkiye',
    coordinates: [36.17, 36.58],
    origin: 'Xangai',
    originCoordinates: [121.4737, 31.2304],
    destination: 'Gaziantep',
    destinationCoordinates: [37.3781, 37.0662],
    product: 'Peças industriais · 1×40′',
    promise: '30 dias',
    modeBefore: 'OCEAN_ROAD',
    modeAfter: 'OCEAN_ROAD',
    historicalImpact: 'Novas reservas foram interrompidas; cargas migraram para Mersin, exigindo reemissão do B/L.',
    sourceLabel: 'Atualização operacional da Maersk',
    sourceUrl: 'https://www.maersk.com/news/articles/2023/02/06/operational-impact-of-earthquake-in-turkey',
    routeBefore: ['Xangai', 'Iskenderun', 'Gaziantep'],
    routeAfter: ['Xangai', 'Mersin', 'Gaziantep'],
    recommendation: 'Mudar o porto de descarga para Mersin e reabrir a decisão se a capacidade se esgotar.',
    etaDelta: '+24–96 h',
    costDelta: '+US$ 0,5–2,5 mil',
    documentChange: 'Entregar B/L original e reemitir POD Mersin',
    trackerBefore: 'Ocean milestones · Iskenderun',
    trackerAfter: 'Mersin terminal + rodoviário',
    accent: '#f0b560',
  },
  {
    id: 'EVT-017',
    shortName: 'NotPetya / Maersk',
    headline: 'O navio segue, mas o sistema da transportadora apaga',
    year: '2017',
    date: '27 jun–9 jul 2017',
    category: 'Ataque cibernético',
    place: 'Rede global da Maersk',
    coordinates: [4.4777, 51.9244],
    origin: 'Rotterdam',
    originCoordinates: [4.4777, 51.9244],
    destination: 'Santos',
    destinationCoordinates: [-46.3289, -23.9608],
    product: 'Químicos regulados · 1×40′',
    promise: '17 dias',
    modeBefore: 'OCEAN',
    modeAfter: 'OCEAN',
    historicalImpact: 'Sistemas globais e terminais ficaram indisponíveis enquanto navios permaneceram manobráveis.',
    sourceLabel: 'Comunicado corporativo da Maersk',
    sourceUrl: 'https://investor.maersk.com/news-releases/news-release-details/cyber-attack-update',
    routeBefore: ['Rotterdam', 'Atlântico', 'Santos'],
    routeAfter: ['Rotterdam', 'Fluxo manual verificado', 'Santos'],
    recommendation: 'Usar continuidade manual somente com referência e aceite de carga perigosa verificados.',
    etaDelta: '+48–168 h',
    costDelta: '+US$ 0–2 mil',
    documentChange: 'Confirmação manual + B/L provisório',
    trackerBefore: 'Portal da transportadora',
    trackerAfter: 'Milestones manuais · confiança baixa',
    accent: '#e05f68',
  },
  {
    id: 'EVT-001',
    shortName: 'Ever Given / Suez',
    headline: 'Um único navio fecha o atalho do comércio global',
    year: '2021',
    date: '23–29 mar 2021',
    category: 'Canal bloqueado',
    place: 'Canal de Suez, Egito',
    coordinates: [32.55, 30.0],
    origin: 'Shenzhen',
    originCoordinates: [114.0579, 22.5431],
    destination: 'Rotterdam',
    destinationCoordinates: [4.4777, 51.9244],
    product: 'Eletrônicos · 1×40′',
    promise: '30 dias',
    modeBefore: 'OCEAN',
    modeAfter: 'OCEAN',
    historicalImpact: 'Navios aguardaram nos dois acessos até o desencalhe e a restauração do canal.',
    sourceLabel: 'International Maritime Organization',
    sourceUrl: 'https://www.imo.org/en/mediacentre/pages/whatsnew-1599.aspx',
    routeBefore: ['Yantian', 'Singapura', 'Suez', 'Rotterdam'],
    routeAfter: ['Yantian', 'Singapura', 'Cabo da Boa Esperança', 'Rotterdam'],
    recommendation: 'Aguardar 24 horas; sem sinal de reabertura, desviar pelo Cabo da Boa Esperança.',
    etaDelta: '+7–14 dias',
    costDelta: '+US$ 1,2–4,5 mil',
    documentChange: 'Endosso de seguro + emenda de rota no B/L',
    trackerBefore: 'Ocean milestones · Suez',
    trackerAfter: 'Ocean control · Cabo',
    accent: '#ffb000',
  },
  {
    id: 'EVT-005',
    shortName: 'Ponte de Baltimore',
    headline: 'O acesso marítimo desaparece antes da atracação',
    year: '2024',
    date: '26 mar–10 jun 2024',
    category: 'Fechamento de acesso portuário',
    place: 'Baltimore, Estados Unidos',
    coordinates: [-76.53, 39.22],
    origin: 'Antuérpia',
    originCoordinates: [4.4025, 51.2194],
    destination: 'Baltimore',
    destinationCoordinates: [-76.6122, 39.2904],
    product: 'Máquina industrial · 1×40′',
    promise: '14 dias',
    modeBefore: 'OCEAN',
    modeAfter: 'OCEAN_ROAD',
    historicalImpact: 'O canal original ficou indisponível; acessos parciais precederam a restauração completa em junho.',
    sourceLabel: 'U.S. Army Corps of Engineers',
    sourceUrl: 'https://www.nab.usace.army.mil/Media/News-Releases/Article/3802402/us-army-corps-of-engineers-announces-full-restoration-of-baltimores-fort-mchenr/',
    routeBefore: ['Antuérpia', 'Atlântico', 'Baltimore'],
    routeAfter: ['Antuérpia', 'Norfolk', 'Baltimore por rodovia'],
    recommendation: 'Descarregar em Norfolk quando o custo de parada superar o prêmio do desvio.',
    etaDelta: '+24–72 h',
    costDelta: '+US$ 1,2–3,5 mil',
    documentChange: 'Alterar porto aduaneiro e B/L',
    trackerBefore: 'Navio + porto Baltimore',
    trackerAfter: 'Terminal Norfolk + drayage',
    accent: '#78b9ff',
  },
  {
    id: 'EVT-004',
    shortName: 'Seca no Canal do Panamá',
    headline: 'A água baixa transforma capacidade em fila',
    year: '2023–24',
    date: 'ago 2023–ago 2024',
    category: 'Restrição climática de capacidade',
    place: 'Canal do Panamá',
    coordinates: [-79.68, 9.08],
    origin: 'Auckland',
    originCoordinates: [174.7633, -36.8485],
    destination: 'Filadélfia',
    destinationCoordinates: [-75.1652, 39.9526],
    product: 'Ingredientes refrigerados',
    promise: '29 dias',
    modeBefore: 'OCEAN',
    modeAfter: 'OCEAN_ROAD',
    historicalImpact: 'Calado, trânsitos diários e slots de reserva foram reduzidos antes da recuperação gradual.',
    sourceLabel: 'Panama Canal Authority',
    sourceUrl: 'https://pancanal.com/en/panama-canal-authority-adapts-to-unprecedented-challenges/',
    routeBefore: ['Auckland', 'Balboa', 'Panamá', 'Filadélfia'],
    routeAfter: ['Auckland', 'Los Angeles', 'ferrovia', 'Filadélfia'],
    recommendation: 'Manter o canal com slot confirmado; sem slot, transbordar somente com handoff de cadeia fria.',
    etaDelta: '+2–10 dias',
    costDelta: '+US$ 2–6 mil',
    documentChange: 'Emenda de slot + registro de cadeia fria',
    trackerBefore: 'Ocean + telemetria reefer',
    trackerAfter: 'Porto + ferrovia + reefer',
    accent: '#65d3a3',
  },
  {
    id: 'EVT-008',
    shortName: 'Chuva extrema em Dubai',
    headline: 'O hub aéreo alaga e a conexão deixa de existir',
    year: '2024',
    date: '16–20 abr 2024',
    category: 'Clima extremo aéreo',
    place: 'Dubai, Emirados Árabes Unidos',
    coordinates: [55.3644, 25.2528],
    origin: 'Bengaluru',
    originCoordinates: [77.5946, 12.9716],
    destination: 'Paris',
    destinationCoordinates: [2.3522, 48.8566],
    product: 'Fármacos refrigerados · 420 kg',
    promise: '24 horas',
    modeBefore: 'AIR',
    modeAfter: 'AIR',
    historicalImpact: 'Desvios, restrições temporárias e milhares de bagagens atrasadas acompanharam a recuperação.',
    sourceLabel: 'Carta oficial da Emirates',
    sourceUrl: 'https://www.emirates.com/media-centre/open-letter-to-customers-from-sir-tim-clark-president-emirates-airline/',
    routeBefore: ['BLR', 'DXB', 'CDG'],
    routeAfter: ['BLR', 'DOH', 'CDG'],
    recommendation: 'Trocar para Doha quando armazenamento refrigerado e uplift estiverem confirmados.',
    etaDelta: '+8–36 h',
    costDelta: '+US$ 2–7 mil',
    documentChange: 'Emenda de AWB + instrução de cadeia fria',
    trackerBefore: 'Air waybill + temperatura',
    trackerAfter: 'Air express + logger contínuo',
    accent: '#59d6e8',
  },
  {
    id: 'EVT-009',
    shortName: 'Inundações na Colúmbia Britânica',
    headline: 'Estradas e trilhos rompem atrás do porto',
    year: '2021',
    date: '14 nov–20 dez 2021',
    category: 'Inundação rodoviária e ferroviária',
    place: 'Vancouver, Canadá',
    coordinates: [-123.1207, 49.2827],
    origin: 'Xangai',
    originCoordinates: [121.4737, 31.2304],
    destination: 'Calgary',
    destinationCoordinates: [-114.0719, 51.0447],
    product: 'Eletrodomésticos · 1×40′',
    promise: '20 dias',
    modeBefore: 'RAIL_OCEAN',
    modeAfter: 'RAIL_OCEAN',
    historicalImpact: 'Pontes e rodovias foram danificadas, reduzindo capacidade ferroviária e congestionando o gateway.',
    sourceLabel: 'Governo da Colúmbia Britânica',
    sourceUrl: 'https://news.gov.bc.ca/releases/2023MOTI0184-001792',
    routeBefore: ['Xangai', 'Vancouver', 'Calgary'],
    routeAfter: ['Xangai', 'Prince Rupert', 'Calgary'],
    recommendation: 'Usar Prince Rupert com slot ferroviário confirmado; senão, priorizar apenas SKUs críticos.',
    etaDelta: '+48–144 h',
    costDelta: '+US$ 1–4 mil',
    documentChange: 'Mudar porto, B/L e waybill ferroviário',
    trackerBefore: 'Ocean + rail Vancouver',
    trackerAfter: 'Ocean + rail Prince Rupert',
    accent: '#80a8ff',
  },
  {
    id: 'EVT-011',
    shortName: 'Paralisação CN + CPKC',
    headline: 'As duas ferrovias nacionais param juntas',
    year: '2024',
    date: '22–26 ago 2024',
    category: 'Paralisação ferroviária',
    place: 'Canadá',
    coordinates: [-106.3468, 56.1304],
    origin: 'Regina',
    originCoordinates: [-104.6189, 50.4452],
    destination: 'Tóquio',
    destinationCoordinates: [139.6917, 35.6895],
    product: 'Ingredientes alimentícios',
    promise: '21 dias',
    modeBefore: 'RAIL_OCEAN',
    modeAfter: 'OCEAN_ROAD',
    historicalImpact: 'As duas grandes redes fecharam; a recuperação operacional continuou após o fim jurídico da paralisação.',
    sourceLabel: 'Governo do Canadá',
    sourceUrl: 'https://search.open.canada.ca/qpnotes/record/aafc-aac%2CAAFC-2025-QP-00031',
    routeBefore: ['Regina', 'Vancouver', 'Tóquio'],
    routeAfter: ['Regina por caminhão', 'Seattle', 'Tóquio'],
    recommendation: 'Aguardar 48 horas; usar Seattle apenas para lotes sem slot ferroviário recuperado.',
    etaDelta: '+24–96 h',
    costDelta: '+US$ 4–12 mil',
    documentChange: 'Novo porto de exportação + B/L',
    trackerBefore: 'Rail car + ocean',
    trackerAfter: 'Truck + terminal Seattle + ocean',
    accent: '#f4c55c',
  },
  {
    id: 'EVT-010',
    shortName: 'Greve portuária ILA',
    headline: 'A costa Atlântica entra em pausa',
    year: '2024',
    date: '1–3 out 2024',
    category: 'Greve portuária',
    place: 'Portos dos EUA, Maine–Texas',
    coordinates: [-81.09, 32.08],
    origin: 'Santos',
    originCoordinates: [-46.3289, -23.9608],
    destination: 'Savannah',
    destinationCoordinates: [-81.0998, 32.0835],
    product: 'Vestuário · 1×40′',
    promise: '18 dias',
    modeBefore: 'OCEAN',
    modeAfter: 'OCEAN_ROAD',
    historicalImpact: 'O trabalho portuário parou e foi retomado após acordo salarial provisório e extensão contratual.',
    sourceLabel: 'International Longshoremen’s Association',
    sourceUrl: 'https://ilaunion.org/joint-statement-regarding-master-contract/',
    routeBefore: ['Santos', 'Atlântico', 'Savannah'],
    routeAfter: ['Santos', 'Halifax', 'Savannah por rodovia'],
    recommendation: 'Aguardar com cobertura de estoque; desviar apenas SKUs que perderiam a janela comercial.',
    etaDelta: '+48–168 h',
    costDelta: '+US$ 1,5–5 mil',
    documentChange: 'Mudar porto de descarga + aviso ao cliente',
    trackerBefore: 'Navio + terminal Savannah',
    trackerAfter: 'Halifax + linehaul rodoviário',
    accent: '#ff8e6d',
  },
];

const englishScenarioCopy: Record<
  string,
  Pick<
    ScenarioFixture,
    | 'shortName'
    | 'headline'
    | 'date'
    | 'category'
    | 'place'
    | 'origin'
    | 'destination'
    | 'product'
    | 'promise'
    | 'historicalImpact'
    | 'sourceLabel'
    | 'routeBefore'
    | 'routeAfter'
    | 'recommendation'
    | 'etaDelta'
    | 'costDelta'
    | 'documentChange'
    | 'trackerBefore'
    | 'trackerAfter'
  >
> = {
  'EVT-012': {
    shortName: 'Delta / CrowdStrike',
    headline: 'A software update grounds the air network',
    date: 'July 19–28, 2024',
    category: 'Global IT outage',
    place: 'Atlanta, United States',
    origin: 'Frankfurt',
    destination: 'Atlanta',
    product: 'AOG part · 180 kg',
    promise: '14 hours',
    historicalImpact: 'Cancellations, delays, and unavailable operational systems during an acute five-day crisis.',
    sourceLabel: 'Delta official advisory',
    routeBefore: ['FRA', 'ATL'],
    routeAfter: ['FRA', 'LHR', 'ATL'],
    recommendation: 'Switch carriers through London while preserving the original AWB audit trail.',
    etaDelta: '+12–48 h',
    costDelta: '+US$4k–12k',
    documentChange: 'Cancel the original AWB and issue a replacement',
    trackerBefore: 'Flight feed · original carrier',
    trackerAfter: 'Air express · LHR connection',
  },
  'EVT-014': {
    shortName: 'Iskenderun earthquake',
    headline: 'The port closes and the Bill of Lading changes',
    date: 'February 6, 2023',
    category: 'Earthquake and port closure',
    place: 'Iskenderun, Türkiye',
    origin: 'Shanghai',
    destination: 'Gaziantep',
    product: 'Industrial parts · 1×40′',
    promise: '30 days',
    historicalImpact: 'New bookings stopped and cargo shifted to Mersin, requiring the Bill of Lading to be reissued.',
    sourceLabel: 'Maersk operational update',
    routeBefore: ['Shanghai', 'Iskenderun', 'Gaziantep'],
    routeAfter: ['Shanghai', 'Mersin', 'Gaziantep'],
    recommendation: 'Change the port of discharge to Mersin and reopen the decision if capacity is exhausted.',
    etaDelta: '+24–96 h',
    costDelta: '+US$0.5k–2.5k',
    documentChange: 'Surrender the original B/L and reissue it with Mersin as POD',
    trackerBefore: 'Ocean milestones · Iskenderun',
    trackerAfter: 'Mersin terminal + road leg',
  },
  'EVT-017': {
    shortName: 'NotPetya / Maersk',
    headline: 'The vessel keeps sailing while the carrier system goes dark',
    date: 'June 27–July 9, 2017',
    category: 'Cyberattack',
    place: 'Maersk global network',
    origin: 'Rotterdam',
    destination: 'Santos',
    product: 'Regulated chemicals · 1×40′',
    promise: '17 days',
    historicalImpact: 'Global systems and terminals became unavailable while vessels remained maneuverable.',
    sourceLabel: 'Maersk corporate update',
    routeBefore: ['Rotterdam', 'Atlantic Ocean', 'Santos'],
    routeAfter: ['Rotterdam', 'Verified manual flow', 'Santos'],
    recommendation: 'Use manual continuity only after references and dangerous-goods acceptance are verified.',
    etaDelta: '+48–168 h',
    costDelta: '+US$0–2k',
    documentChange: 'Manual confirmation plus provisional B/L',
    trackerBefore: 'Carrier portal',
    trackerAfter: 'Manual milestones · low confidence',
  },
  'EVT-001': {
    shortName: 'Ever Given / Suez',
    headline: 'One vessel closes global trade’s shortcut',
    date: 'March 23–29, 2021',
    category: 'Canal blockage',
    place: 'Suez Canal, Egypt',
    origin: 'Shenzhen',
    destination: 'Rotterdam',
    product: 'Electronics · 1×40′',
    promise: '30 days',
    historicalImpact: 'Vessels waited at both entrances until the ship was refloated and the canal reopened.',
    sourceLabel: 'International Maritime Organization',
    routeBefore: ['Yantian', 'Singapore', 'Suez', 'Rotterdam'],
    routeAfter: ['Yantian', 'Singapore', 'Cape of Good Hope', 'Rotterdam'],
    recommendation: 'Wait 24 hours; if reopening remains uncertain, divert around the Cape of Good Hope.',
    etaDelta: '+7–14 days',
    costDelta: '+US$1.2k–4.5k',
    documentChange: 'Insurance endorsement plus B/L route amendment',
    trackerBefore: 'Ocean milestones · Suez',
    trackerAfter: 'Ocean control · Cape route',
  },
  'EVT-005': {
    shortName: 'Baltimore bridge',
    headline: 'Maritime access disappears before berthing',
    date: 'March 26–June 10, 2024',
    category: 'Port access closure',
    place: 'Baltimore, United States',
    origin: 'Antwerp',
    destination: 'Baltimore',
    product: 'Industrial machine · 1×40′',
    promise: '14 days',
    historicalImpact: 'The original channel became unavailable; partial access preceded full restoration in June.',
    sourceLabel: 'U.S. Army Corps of Engineers',
    routeBefore: ['Antwerp', 'Atlantic Ocean', 'Baltimore'],
    routeAfter: ['Antwerp', 'Norfolk', 'Baltimore by road'],
    recommendation: 'Discharge in Norfolk when stoppage cost exceeds the diversion premium.',
    etaDelta: '+24–72 h',
    costDelta: '+US$1.2k–3.5k',
    documentChange: 'Change customs port and Bill of Lading',
    trackerBefore: 'Vessel + Baltimore port',
    trackerAfter: 'Norfolk terminal + drayage',
  },
  'EVT-004': {
    shortName: 'Panama Canal drought',
    headline: 'Low water turns capacity into a queue',
    date: 'August 2023–August 2024',
    category: 'Climate-driven capacity restriction',
    place: 'Panama Canal',
    origin: 'Auckland',
    destination: 'Philadelphia',
    product: 'Refrigerated ingredients',
    promise: '29 days',
    historicalImpact: 'Draft, daily transits, and booking slots were reduced before a gradual recovery.',
    sourceLabel: 'Panama Canal Authority',
    routeBefore: ['Auckland', 'Balboa', 'Panama Canal', 'Philadelphia'],
    routeAfter: ['Auckland', 'Los Angeles', 'Rail', 'Philadelphia'],
    recommendation: 'Keep the canal with a confirmed slot; otherwise transship only with a verified cold-chain handoff.',
    etaDelta: '+2–10 days',
    costDelta: '+US$2k–6k',
    documentChange: 'Slot amendment plus cold-chain record',
    trackerBefore: 'Ocean + reefer telemetry',
    trackerAfter: 'Port + rail + reefer',
  },
  'EVT-008': {
    shortName: 'Extreme rain in Dubai',
    headline: 'The air hub floods and the connection disappears',
    date: 'April 16–20, 2024',
    category: 'Extreme aviation weather',
    place: 'Dubai, United Arab Emirates',
    origin: 'Bengaluru',
    destination: 'Paris',
    product: 'Cold-chain pharmaceuticals · 420 kg',
    promise: '24 hours',
    historicalImpact: 'Diversions, temporary restrictions, and thousands of delayed bags accompanied the recovery.',
    sourceLabel: 'Emirates official letter',
    routeBefore: ['BLR', 'DXB', 'CDG'],
    routeAfter: ['BLR', 'DOH', 'CDG'],
    recommendation: 'Switch through Doha after refrigerated storage and uplift are confirmed.',
    etaDelta: '+8–36 h',
    costDelta: '+US$2k–7k',
    documentChange: 'AWB amendment plus cold-chain instruction',
    trackerBefore: 'Air waybill + temperature',
    trackerAfter: 'Air express + continuous logger',
  },
  'EVT-009': {
    shortName: 'British Columbia floods',
    headline: 'Roads and rails break behind the port',
    date: 'November 14–December 20, 2021',
    category: 'Road and rail flooding',
    place: 'Vancouver, Canada',
    origin: 'Shanghai',
    destination: 'Calgary',
    product: 'Home appliances · 1×40′',
    promise: '20 days',
    historicalImpact: 'Damaged bridges and highways reduced rail capacity and congested the gateway.',
    sourceLabel: 'Government of British Columbia',
    routeBefore: ['Shanghai', 'Vancouver', 'Calgary'],
    routeAfter: ['Shanghai', 'Prince Rupert', 'Calgary'],
    recommendation: 'Use Prince Rupert with a confirmed rail slot; otherwise prioritize critical SKUs only.',
    etaDelta: '+48–144 h',
    costDelta: '+US$1k–4k',
    documentChange: 'Change port, B/L, and rail waybill',
    trackerBefore: 'Ocean + Vancouver rail',
    trackerAfter: 'Ocean + Prince Rupert rail',
  },
  'EVT-011': {
    shortName: 'CN + CPKC shutdown',
    headline: 'Both national railways stop together',
    date: 'August 22–26, 2024',
    category: 'Railway shutdown',
    place: 'Canada',
    origin: 'Regina',
    destination: 'Tokyo',
    product: 'Food ingredients',
    promise: '21 days',
    historicalImpact: 'Both major networks closed; operational recovery continued after the legal shutdown ended.',
    sourceLabel: 'Government of Canada',
    routeBefore: ['Regina', 'Vancouver', 'Tokyo'],
    routeAfter: ['Regina by truck', 'Seattle', 'Tokyo'],
    recommendation: 'Wait 48 hours; use Seattle only for lots without a recovered rail slot.',
    etaDelta: '+24–96 h',
    costDelta: '+US$4k–12k',
    documentChange: 'New export port plus Bill of Lading',
    trackerBefore: 'Rail car + ocean',
    trackerAfter: 'Truck + Seattle terminal + ocean',
  },
  'EVT-010': {
    shortName: 'ILA port strike',
    headline: 'The Atlantic coast pauses',
    date: 'October 1–3, 2024',
    category: 'Port strike',
    place: 'U.S. ports, Maine–Texas',
    origin: 'Santos',
    destination: 'Savannah',
    product: 'Apparel · 1×40′',
    promise: '18 days',
    historicalImpact: 'Port work stopped and resumed after a tentative wage agreement and contract extension.',
    sourceLabel: 'International Longshoremen’s Association',
    routeBefore: ['Santos', 'Atlantic Ocean', 'Savannah'],
    routeAfter: ['Santos', 'Halifax', 'Savannah by road'],
    recommendation: 'Wait with inventory coverage; divert only SKUs that would miss their commercial window.',
    etaDelta: '+48–168 h',
    costDelta: '+US$1.5k–5k',
    documentChange: 'Change port of discharge plus customer notice',
    trackerBefore: 'Vessel + Savannah terminal',
    trackerAfter: 'Halifax + road linehaul',
  },
};

const canonicalEventStartDates: Record<string, string> = {
  'EVT-012': '2024-07-19',
  'EVT-014': '2023-02-06',
  'EVT-017': '2017-06-27',
  'EVT-001': '2021-03-23',
  'EVT-005': '2024-03-26',
  'EVT-004': '2023-08-01',
  'EVT-008': '2024-04-16',
  'EVT-009': '2021-11-14',
  'EVT-011': '2024-08-22',
  'EVT-010': '2024-10-01',
};

export const scenarios: Scenario[] = scenarioFixtures.map((scenario) => {
  const copy = englishScenarioCopy[scenario.id];
  const translated = { ...scenario, ...copy };
  const eventStartDate = canonicalEventStartDates[scenario.id];
  if (!eventStartDate) throw new Error(`Scenario ${scenario.id} is missing its canonical event start date.`);

  return {
    ...translated,
    eventStartDate,
    provenance: {
      sourceTitle: translated.sourceLabel,
      sourceUrl: translated.sourceUrl,
      eventDate: eventStartDate,
      publicationDate: 'UNKNOWN',
      retrievedDate: 'UNKNOWN',
      confidence: 'MEDIUM',
      classification: 'HISTORICAL_FACT',
    },
  };
});

export const modeLabel: Record<TransportMode, string> = {
  AIR: 'Air',
  OCEAN: 'Ocean',
  OCEAN_ROAD: 'Ocean + road',
  RAIL_OCEAN: 'Rail + ocean',
};
