export type TransportMode = 'AIR' | 'OCEAN' | 'OCEAN_ROAD' | 'RAIL_OCEAN';

export type Scenario = {
  id: string;
  shortName: string;
  headline: string;
  year: string;
  date: string;
  category: string;
  place: string;
  coordinates: [number, number];
  origin: string;
  originCoordinates: [number, number];
  destination: string;
  destinationCoordinates: [number, number];
  product: string;
  promise: string;
  modeBefore: TransportMode;
  modeAfter: TransportMode;
  historicalImpact: string;
  sourceLabel: string;
  sourceUrl: string;
  routeBefore: string[];
  routeAfter: string[];
  recommendation: string;
  etaDelta: string;
  costDelta: string;
  documentChange: string;
  trackerBefore: string;
  trackerAfter: string;
  accent: string;
};

export const scenarios: Scenario[] = [
  {
    id: 'EVT-012',
    shortName: 'Delta / CrowdStrike',
    headline: 'Uma atualização paralisa a malha aérea',
    year: '2024',
    date: '19–28 jul 2024',
    category: 'Pane global de TI',
    place: 'Atlanta, Estados Unidos',
    coordinates: [-84.4277, 33.6407],
    origin: 'Frankfurt',
    originCoordinates: [8.5706, 50.0333],
    destination: 'Atlanta',
    destinationCoordinates: [-84.4277, 33.6407],
    product: 'Peça AOG · 180 kg',
    promise: '14 horas',
    modeBefore: 'AIR',
    modeAfter: 'AIR',
    historicalImpact: 'Cancelamentos, atrasos e sistemas operacionais indisponíveis durante uma crise aguda de cinco dias.',
    sourceLabel: 'Alerta oficial da Delta',
    sourceUrl: 'https://www.delta.com/us/en/advisories/other-alerts/july-2024-travel-disruption',
    routeBefore: ['FRA', 'ATL'],
    routeAfter: ['FRA', 'LHR', 'ATL'],
    recommendation: 'Trocar a companhia via Londres e preservar o histórico do AWB original.',
    etaDelta: '+12–48 h',
    costDelta: '+US$ 4–12 mil',
    documentChange: 'Cancelar AWB original e emitir novo AWB',
    trackerBefore: 'Flight feed · companhia original',
    trackerAfter: 'Air express · conexão LHR',
    accent: '#ff7a93',
  },
  {
    id: 'EVT-014',
    shortName: 'Terremoto de Iskenderun',
    headline: 'O porto fecha e o conhecimento de embarque muda',
    year: '2023',
    date: '6 fev 2023',
    category: 'Terremoto + fechamento portuário',
    place: 'Iskenderun, Türkiye',
    coordinates: [36.17, 36.58],
    origin: 'Xangai',
    originCoordinates: [121.4737, 31.2304],
    destination: 'Gaziantep',
    destinationCoordinates: [37.3781, 37.0662],
    product: 'Peças industriais · 1×40′',
    promise: '30 dias',
    modeBefore: 'OCEAN_ROAD',
    modeAfter: 'OCEAN_ROAD',
    historicalImpact: 'Novas reservas foram interrompidas; cargas migraram para Mersin, exigindo reemissão do B/L.',
    sourceLabel: 'Atualização operacional da Maersk',
    sourceUrl: 'https://www.maersk.com/news/articles/2023/02/06/operational-impact-of-earthquake-in-turkey',
    routeBefore: ['Xangai', 'Iskenderun', 'Gaziantep'],
    routeAfter: ['Xangai', 'Mersin', 'Gaziantep'],
    recommendation: 'Mudar o porto de descarga para Mersin e reabrir a decisão se a capacidade se esgotar.',
    etaDelta: '+24–96 h',
    costDelta: '+US$ 0,5–2,5 mil',
    documentChange: 'Entregar B/L original e reemitir POD Mersin',
    trackerBefore: 'Ocean milestones · Iskenderun',
    trackerAfter: 'Mersin terminal + rodoviário',
    accent: '#f0b560',
  },
  {
    id: 'EVT-017',
    shortName: 'NotPetya / Maersk',
    headline: 'O navio segue, mas o sistema da transportadora apaga',
    year: '2017',
    date: '27 jun–9 jul 2017',
    category: 'Ataque cibernético',
    place: 'Rede global da Maersk',
    coordinates: [4.4777, 51.9244],
    origin: 'Rotterdam',
    originCoordinates: [4.4777, 51.9244],
    destination: 'Santos',
    destinationCoordinates: [-46.3289, -23.9608],
    product: 'Químicos regulados · 1×40′',
    promise: '17 dias',
    modeBefore: 'OCEAN',
    modeAfter: 'OCEAN',
    historicalImpact: 'Sistemas globais e terminais ficaram indisponíveis enquanto navios permaneceram manobráveis.',
    sourceLabel: 'Comunicado corporativo da Maersk',
    sourceUrl: 'https://investor.maersk.com/news-releases/news-release-details/cyber-attack-update',
    routeBefore: ['Rotterdam', 'Atlântico', 'Santos'],
    routeAfter: ['Rotterdam', 'Fluxo manual verificado', 'Santos'],
    recommendation: 'Usar continuidade manual somente com referência e aceite de carga perigosa verificados.',
    etaDelta: '+48–168 h',
    costDelta: '+US$ 0–2 mil',
    documentChange: 'Confirmação manual + B/L provisório',
    trackerBefore: 'Portal da transportadora',
    trackerAfter: 'Milestones manuais · confiança baixa',
    accent: '#e05f68',
  },
  {
    id: 'EVT-001',
    shortName: 'Ever Given / Suez',
    headline: 'Um único navio fecha o atalho do comércio global',
    year: '2021',
    date: '23–29 mar 2021',
    category: 'Canal bloqueado',
    place: 'Canal de Suez, Egito',
    coordinates: [32.55, 30.0],
    origin: 'Shenzhen',
    originCoordinates: [114.0579, 22.5431],
    destination: 'Rotterdam',
    destinationCoordinates: [4.4777, 51.9244],
    product: 'Eletrônicos · 1×40′',
    promise: '30 dias',
    modeBefore: 'OCEAN',
    modeAfter: 'OCEAN',
    historicalImpact: 'Navios aguardaram nos dois acessos até o desencalhe e a restauração do canal.',
    sourceLabel: 'International Maritime Organization',
    sourceUrl: 'https://www.imo.org/en/mediacentre/pages/whatsnew-1599.aspx',
    routeBefore: ['Yantian', 'Singapura', 'Suez', 'Rotterdam'],
    routeAfter: ['Yantian', 'Singapura', 'Cabo da Boa Esperança', 'Rotterdam'],
    recommendation: 'Aguardar 24 horas; sem sinal de reabertura, desviar pelo Cabo da Boa Esperança.',
    etaDelta: '+7–14 dias',
    costDelta: '+US$ 1,2–4,5 mil',
    documentChange: 'Endosso de seguro + emenda de rota no B/L',
    trackerBefore: 'Ocean milestones · Suez',
    trackerAfter: 'Ocean control · Cabo',
    accent: '#ffb000',
  },
  {
    id: 'EVT-005',
    shortName: 'Ponte de Baltimore',
    headline: 'O acesso marítimo desaparece antes da atracação',
    year: '2024',
    date: '26 mar–10 jun 2024',
    category: 'Fechamento de acesso portuário',
    place: 'Baltimore, Estados Unidos',
    coordinates: [-76.53, 39.22],
    origin: 'Antuérpia',
    originCoordinates: [4.4025, 51.2194],
    destination: 'Baltimore',
    destinationCoordinates: [-76.6122, 39.2904],
    product: 'Máquina industrial · 1×40′',
    promise: '14 dias',
    modeBefore: 'OCEAN',
    modeAfter: 'OCEAN_ROAD',
    historicalImpact: 'O canal original ficou indisponível; acessos parciais precederam a restauração completa em junho.',
    sourceLabel: 'U.S. Army Corps of Engineers',
    sourceUrl: 'https://www.nab.usace.army.mil/Media/News-Releases/Article/3802402/us-army-corps-of-engineers-announces-full-restoration-of-baltimores-fort-mchenr/',
    routeBefore: ['Antuérpia', 'Atlântico', 'Baltimore'],
    routeAfter: ['Antuérpia', 'Norfolk', 'Baltimore por rodovia'],
    recommendation: 'Descarregar em Norfolk quando o custo de parada superar o prêmio do desvio.',
    etaDelta: '+24–72 h',
    costDelta: '+US$ 1,2–3,5 mil',
    documentChange: 'Alterar porto aduaneiro e B/L',
    trackerBefore: 'Navio + porto Baltimore',
    trackerAfter: 'Terminal Norfolk + drayage',
    accent: '#78b9ff',
  },
  {
    id: 'EVT-004',
    shortName: 'Seca no Canal do Panamá',
    headline: 'A água baixa transforma capacidade em fila',
    year: '2023–24',
    date: 'ago 2023–ago 2024',
    category: 'Restrição climática de capacidade',
    place: 'Canal do Panamá',
    coordinates: [-79.68, 9.08],
    origin: 'Auckland',
    originCoordinates: [174.7633, -36.8485],
    destination: 'Filadélfia',
    destinationCoordinates: [-75.1652, 39.9526],
    product: 'Ingredientes refrigerados',
    promise: '29 dias',
    modeBefore: 'OCEAN',
    modeAfter: 'OCEAN_ROAD',
    historicalImpact: 'Calado, trânsitos diários e slots de reserva foram reduzidos antes da recuperação gradual.',
    sourceLabel: 'Panama Canal Authority',
    sourceUrl: 'https://pancanal.com/en/panama-canal-authority-adapts-to-unprecedented-challenges/',
    routeBefore: ['Auckland', 'Balboa', 'Panamá', 'Filadélfia'],
    routeAfter: ['Auckland', 'Los Angeles', 'ferrovia', 'Filadélfia'],
    recommendation: 'Manter o canal com slot confirmado; sem slot, transbordar somente com handoff de cadeia fria.',
    etaDelta: '+2–10 dias',
    costDelta: '+US$ 2–6 mil',
    documentChange: 'Emenda de slot + registro de cadeia fria',
    trackerBefore: 'Ocean + telemetria reefer',
    trackerAfter: 'Porto + ferrovia + reefer',
    accent: '#65d3a3',
  },
  {
    id: 'EVT-008',
    shortName: 'Chuva extrema em Dubai',
    headline: 'O hub aéreo alaga e a conexão deixa de existir',
    year: '2024',
    date: '16–20 abr 2024',
    category: 'Clima extremo aéreo',
    place: 'Dubai, Emirados Árabes Unidos',
    coordinates: [55.3644, 25.2528],
    origin: 'Bengaluru',
    originCoordinates: [77.5946, 12.9716],
    destination: 'Paris',
    destinationCoordinates: [2.3522, 48.8566],
    product: 'Fármacos refrigerados · 420 kg',
    promise: '24 horas',
    modeBefore: 'AIR',
    modeAfter: 'AIR',
    historicalImpact: 'Desvios, restrições temporárias e milhares de bagagens atrasadas acompanharam a recuperação.',
    sourceLabel: 'Carta oficial da Emirates',
    sourceUrl: 'https://www.emirates.com/media-centre/open-letter-to-customers-from-sir-tim-clark-president-emirates-airline/',
    routeBefore: ['BLR', 'DXB', 'CDG'],
    routeAfter: ['BLR', 'DOH', 'CDG'],
    recommendation: 'Trocar para Doha quando armazenamento refrigerado e uplift estiverem confirmados.',
    etaDelta: '+8–36 h',
    costDelta: '+US$ 2–7 mil',
    documentChange: 'Emenda de AWB + instrução de cadeia fria',
    trackerBefore: 'Air waybill + temperatura',
    trackerAfter: 'Air express + logger contínuo',
    accent: '#59d6e8',
  },
  {
    id: 'EVT-009',
    shortName: 'Inundações na Colúmbia Britânica',
    headline: 'Estradas e trilhos rompem atrás do porto',
    year: '2021',
    date: '14 nov–20 dez 2021',
    category: 'Inundação rodoviária e ferroviária',
    place: 'Vancouver, Canadá',
    coordinates: [-123.1207, 49.2827],
    origin: 'Xangai',
    originCoordinates: [121.4737, 31.2304],
    destination: 'Calgary',
    destinationCoordinates: [-114.0719, 51.0447],
    product: 'Eletrodomésticos · 1×40′',
    promise: '20 dias',
    modeBefore: 'RAIL_OCEAN',
    modeAfter: 'RAIL_OCEAN',
    historicalImpact: 'Pontes e rodovias foram danificadas, reduzindo capacidade ferroviária e congestionando o gateway.',
    sourceLabel: 'Governo da Colúmbia Britânica',
    sourceUrl: 'https://news.gov.bc.ca/releases/2023MOTI0184-001792',
    routeBefore: ['Xangai', 'Vancouver', 'Calgary'],
    routeAfter: ['Xangai', 'Prince Rupert', 'Calgary'],
    recommendation: 'Usar Prince Rupert com slot ferroviário confirmado; senão, priorizar apenas SKUs críticos.',
    etaDelta: '+48–144 h',
    costDelta: '+US$ 1–4 mil',
    documentChange: 'Mudar porto, B/L e waybill ferroviário',
    trackerBefore: 'Ocean + rail Vancouver',
    trackerAfter: 'Ocean + rail Prince Rupert',
    accent: '#80a8ff',
  },
  {
    id: 'EVT-011',
    shortName: 'Paralisação CN + CPKC',
    headline: 'As duas ferrovias nacionais param juntas',
    year: '2024',
    date: '22–26 ago 2024',
    category: 'Paralisação ferroviária',
    place: 'Canadá',
    coordinates: [-106.3468, 56.1304],
    origin: 'Regina',
    originCoordinates: [-104.6189, 50.4452],
    destination: 'Tóquio',
    destinationCoordinates: [139.6917, 35.6895],
    product: 'Ingredientes alimentícios',
    promise: '21 dias',
    modeBefore: 'RAIL_OCEAN',
    modeAfter: 'OCEAN_ROAD',
    historicalImpact: 'As duas grandes redes fecharam; a recuperação operacional continuou após o fim jurídico da paralisação.',
    sourceLabel: 'Governo do Canadá',
    sourceUrl: 'https://search.open.canada.ca/qpnotes/record/aafc-aac%2CAAFC-2025-QP-00031',
    routeBefore: ['Regina', 'Vancouver', 'Tóquio'],
    routeAfter: ['Regina por caminhão', 'Seattle', 'Tóquio'],
    recommendation: 'Aguardar 48 horas; usar Seattle apenas para lotes sem slot ferroviário recuperado.',
    etaDelta: '+24–96 h',
    costDelta: '+US$ 4–12 mil',
    documentChange: 'Novo porto de exportação + B/L',
    trackerBefore: 'Rail car + ocean',
    trackerAfter: 'Truck + terminal Seattle + ocean',
    accent: '#f4c55c',
  },
  {
    id: 'EVT-010',
    shortName: 'Greve portuária ILA',
    headline: 'A costa Atlântica entra em pausa',
    year: '2024',
    date: '1–3 out 2024',
    category: 'Greve portuária',
    place: 'Portos dos EUA, Maine–Texas',
    coordinates: [-81.09, 32.08],
    origin: 'Santos',
    originCoordinates: [-46.3289, -23.9608],
    destination: 'Savannah',
    destinationCoordinates: [-81.0998, 32.0835],
    product: 'Vestuário · 1×40′',
    promise: '18 dias',
    modeBefore: 'OCEAN',
    modeAfter: 'OCEAN_ROAD',
    historicalImpact: 'O trabalho portuário parou e foi retomado após acordo salarial provisório e extensão contratual.',
    sourceLabel: 'International Longshoremen’s Association',
    sourceUrl: 'https://ilaunion.org/joint-statement-regarding-master-contract/',
    routeBefore: ['Santos', 'Atlântico', 'Savannah'],
    routeAfter: ['Santos', 'Halifax', 'Savannah por rodovia'],
    recommendation: 'Aguardar com cobertura de estoque; desviar apenas SKUs que perderiam a janela comercial.',
    etaDelta: '+48–168 h',
    costDelta: '+US$ 1,5–5 mil',
    documentChange: 'Mudar porto de descarga + aviso ao cliente',
    trackerBefore: 'Navio + terminal Savannah',
    trackerAfter: 'Halifax + linehaul rodoviário',
    accent: '#ff8e6d',
  },
];

export const modeLabel: Record<TransportMode, string> = {
  AIR: 'Aéreo',
  OCEAN: 'Marítimo',
  OCEAN_ROAD: 'Marítimo + rodoviário',
  RAIL_OCEAN: 'Ferroviário + marítimo',
};
